# Config file for automatic testing at travis-ci.org
# This file will be regenerated if you run travis_pypi_setup.py

language: python
python:
  - "3.5"
  - "3.4"
  - "3.3"
  - "2.7"
  - "2.6"
  # does not have headers provided, please ask https://launchpad.net/~pypy/+archive/ppa
  # maintainers to fix their pypy-dev package.
  - "pypy"

env:
  matrix:
  - TOXENV=py35
  - TOXENV=py34
  - TOXENV=py33
  - TOXENV=py27
  - TOXENV=py26
  - TOXENV=pypy
  global:
    secure: PUynuK5RJA+tCe5OW6OL3XRFHmd6hj5iRgGyI9l40cy0THRX3Y+DCbvh+2BCHV+zFmhkGZV3px5YqemhbL+9fPSrg73AxVizKDtHxhT8vk0OHKniaw9t4MMdVcI4V2y5p891q0Nh+r69tV4T8p+AfgtTovPFp+4vaN7zlMpTlICzP5zcKTJV25J4oRhIyuxdh4G7IOd49LawRNIZ5O3VnpvXXfZrGB1K85QICKIKYfZpGVOov0x5iLfdEa9xFWFkxpRKAnjwZw1mtoNUOma+VAD89Z8nZJAytVT7lnBxgm7pLl55bHWVBeIe8peTdyoCp8J4dj6XYC1Ps+YBqxCBgPCyPhfpeYn6qXKGElFBNGRHicyjpYSJY1DKUAl5HgmOUiQIE71N2AdIL6f12GKqeXqYT37HWPcMAqR0zQmVvyzvPBsCzMuUUV0oHz089yihI+7WrWmHYKE2tA/KHDhzDYrxKzvy7fF4g6ixSLtonevfDyyIVWHVr3jgjLua4LgulnDMG6cKL3JoxID6O5cIw5Z/Aw/j+OirtCrtyUJprgsXyP4E02G5nBrcdAJ9q/lg5BKqbtdeb8EuuPisL33pKxEvtZ5H9Sju6w8eprFh15YStifv9qOcGBlnMHs2ud3/+V/2Vsq+y+puozrGMGW9iA9PHCli5SkXa3h6cd5/5xo=

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
  - pip install -U pip
  - pip install -r requirements_dev.txt
  - python setup.py develop

# command to run tests, e.g. python setup.py test
script:
  - tox
  - prospector --zero-exit --strictness veryhigh > lint.txt
  - inline-plz --repo-slug=$TRAVIS_REPO_SLUG --token=$GITHUB_TOKEN --pr=$TRAVIS_PULL_REQUEST --parser=prospector --interface=github --filename=lint.txt

# After you create the Github repo and add it to Travis, run the
# travis_pypi_setup.py script to finish PyPI deployment setup
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: guykisel
  password:
    secure: PLEASE_REPLACE_ME
  on:
    tags: true
    repo: guykisel/inline-plz
    condition: $TOXENV == py27

addons:
  apt:
    sources:
      - deadsnakes
    packages:
      - python3.5-dev
