addons:
  apt:
    packages:
    - python3.5-dev
    sources:
    - deadsnakes
deploy:
  on:
    condition: $TRAVIS_PYTHON_VERSION == 2.7
    repo: guykisel/inline-plz
    tags: true
  distributions: sdist bdist_wheel
  password:
    secure: diMyD7C2XIof4ZdCxyrVvI1GJc2mt2EKhtsQF4tdkhS2ODZ3h+6aplLMJtCvJmSfy89iE1KPCw4I3HAO29bKMXMbz85TGstf4HtTGcVPSSqw7g50lHZlXmm+0ykXhScktNxBDzW220cdyo6ztcTRkEHWjCanYTx0g0eHS4qMqCSxuEsv+Ma+IFbcES40but15aKqm4VBXou5o6iIyy/EIJ/UzDPDsesFPfCOgtNwiN8/FvCulprKzFi5yffcDRO0yyYkNC7H/uTNnBHPFIdWqSmHUqqFnlnSgDE1XtPEGBENNYL7XGxUV3rBYsCLf2kmMJni5MZGETAX2a8qEDckpvm15tceOq1ebl4i2KUl3PPC/iNR10rlNytSbsSfH8oCbUTEZIdJu13cOZ9PAM7YTqwIQq9nv4FYt+qsgT7+gFA6RvY83fQGSWDkZjXWF585aMDIFH3f2l2nt4v0PZIhQO9CF3yJqlXKz6BmJPE5cZ1GOiY7y616Tgnf11rubqh1MY8RSoZwtgOOAi3TLKsluaDxDi8fGM1toW5ClSicFVtbppzvsRqBbYDZds0f187oxHYDdhg87kqGwTFmYBtHYxU1JC245H82z8LeKaT98Cwvl+1OkV/6fmgi5Ii3vrDdWihmOeQvl6GWCR1QhuITBestisJlUBWkhUU7xBEmIME=
  provider: pypi
  user: guykisel
env:
  global:
    secure: PUynuK5RJA+tCe5OW6OL3XRFHmd6hj5iRgGyI9l40cy0THRX3Y+DCbvh+2BCHV+zFmhkGZV3px5YqemhbL+9fPSrg73AxVizKDtHxhT8vk0OHKniaw9t4MMdVcI4V2y5p891q0Nh+r69tV4T8p+AfgtTovPFp+4vaN7zlMpTlICzP5zcKTJV25J4oRhIyuxdh4G7IOd49LawRNIZ5O3VnpvXXfZrGB1K85QICKIKYfZpGVOov0x5iLfdEa9xFWFkxpRKAnjwZw1mtoNUOma+VAD89Z8nZJAytVT7lnBxgm7pLl55bHWVBeIe8peTdyoCp8J4dj6XYC1Ps+YBqxCBgPCyPhfpeYn6qXKGElFBNGRHicyjpYSJY1DKUAl5HgmOUiQIE71N2AdIL6f12GKqeXqYT37HWPcMAqR0zQmVvyzvPBsCzMuUUV0oHz089yihI+7WrWmHYKE2tA/KHDhzDYrxKzvy7fF4g6ixSLtonevfDyyIVWHVr3jgjLua4LgulnDMG6cKL3JoxID6O5cIw5Z/Aw/j+OirtCrtyUJprgsXyP4E02G5nBrcdAJ9q/lg5BKqbtdeb8EuuPisL33pKxEvtZ5H9Sju6w8eprFh15YStifv9qOcGBlnMHs2ud3/+V/2Vsq+y+puozrGMGW9iA9PHCli5SkXa3h6cd5/5xo=
install:
- pip install -U pip
- pip install -r requirements_dev.txt
- python setup.py develop
language: python
python:
- '3.5'
- '3.4'
- '3.3'
- '2.7'
script:
- tox
- inline-plz --dryrun --autorun
- inline-plz --autorun
